name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to AWS via SSH
        env:
          PRIVATE_KEY: ${{ secrets.JANAKA_AWS_SSH_KEY }}
          HOST: ${{ secrets.JANAKA_AWS_HOST }}
          USER: ${{ secrets.JANAKA_AWS_USER }}
          DEPLOY_DIR: /www/wwwroot/janaka.linkpc.net
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          rsync -avz --delete --exclude=".well-known" --exclude=".user.ini" -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" ./ $USER@$HOST:$DEPLOY_DIR
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
            cd $DEPLOY_DIR
          EOF
          rm private_key.pem